# Change these first
owner: lerndmina # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: imadam.io
    url: https://imadam.io
  - name: commands.wiki
    url: https://commands.wiki
  - name: shrt.zip
    url: https://shrt.zip/dashboard
  - name: Thalwyrn
    url: https://thalwyrn.com/index.php?route=/api/v2/info
    expectedStatusCodes:
      - 400
      - 200
      - 201
  # - name: Cors-Proxy
  #   url: $CORS_PROXY_URL
  - name: MinIO
    url: https://console.minioapp.uk
  - name: Handy (My Personal Server)
    url: $HANDY_URL
  # - name: Mini (A literal Mac Mini)
  #   url: $MINISERVER_URL
  - name: Seedbox (for my linux ISOs)
    url: $SEEDBOX_URL
    expectedStatusCodes:
      - 502
      - 200
      - 201

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.imadam.io
  # baseUrl: /uptime
  logoUrl: https://icons.duckduckgo.com/ip3/imadam.io.ico
  name: Statuspage
  theme: ocean
  introTitle: "Are We Up?"
  introMessage: "Hey there! Just checking in to see if our apps are behaving themselves. This page will give you the lowdown on whether everything's running smoothly or if we're having a bit of a hiccup. We're doing our best to keep things up and running, but if you spot any issues, let us know!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
